FROM node:18-slim

WORKDIR /usr/src/app/app-ui

COPY package*.json ./

#commonde ci-dessous uniquement sur DEV
RUN npm install --save-dev @angular/cli@latest

RUN npm install -g @angular/cli @angular-devkit/build-angular && npm install


EXPOSE 4200

CMD ["npm", "start"]